# Generated by Django 2.1.7 on 2019-03-24 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('link', models.CharField(blank=True, max_length=255)),
                ('finished', models.DateField()),
                ('created', models.DateField()),
                ('updated', models.DateField()),
                ('deleted', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('link', models.CharField(blank=True, max_length=255, null=True)),
                ('created', models.DateField()),
                ('updated', models.DateField()),
                ('deleted', models.DateField()),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='platform',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Platform'),
        ),
    ]
