# Generated by Django 2.1.7 on 2019-03-20 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SocialNetwork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('alias', models.CharField(max_length=64)),
                ('icon', models.CharField(max_length=32)),
                ('link', models.CharField(max_length=255)),
                ('position', models.IntegerField(max_length=2)),
                ('created', models.DateField()),
                ('updated', models.DateField()),
                ('deleted', models.DateField()),
            ],
        ),
    ]
