# Generated by Django 2.1.7 on 2019-03-21 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socials', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialnetwork',
            name='position',
            field=models.IntegerField(),
        ),
    ]
