# Generated by Django 2.1.7 on 2019-03-20 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='link',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
