# Generated by Django 2.1.7 on 2019-03-24 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('enterprise', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job', models.CharField(max_length=64)),
                ('description', models.CharField(max_length=255)),
                ('text', models.TextField()),
                ('started_at', models.DateField()),
                ('finished_at', models.DateField(blank=True, null=True)),
                ('created', models.DateField()),
                ('updated', models.DateField()),
                ('deleted', models.DateField()),
                ('enterprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enterprise.Enterprise')),
            ],
        ),
    ]
