# Generated by Django 2.1.7 on 2019-03-26 18:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enterprise',
            name='created',
        ),
        migrations.RemoveField(
            model_name='enterprise',
            name='deleted',
        ),
        migrations.RemoveField(
            model_name='enterprise',
            name='updated',
        ),
        migrations.AddField(
            model_name='enterprise',
            name='created_at',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='enterprise',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='enterprise',
            name='updated_at',
            field=models.DateField(auto_now=True),
        ),
    ]
